In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [3]:
arr2 = arr1
arr2

array([1, 2, 3, 4])

In [4]:
## Addrress for both arrays are same when we are assigning 
print(id(arr1))
print(id(arr2))

2319930079232
2319930079232


In [5]:
## Shalow Copy
arr2 = arr1.view()

In [6]:
## Addrress for both arrays are different now when we are making shallow copy

print(id(arr1))

print(id(arr2))


2319930079232
2319930143968


In [12]:
## But if we change value in one array , it will change in another array as well.

arr2[2] = 100
arr1[3] = 200

print(arr1)
print(arr2)

[  1   2 100 200]
[  1   2 100 200]


In [13]:
# To avoid above problem we can use deep copy
arr2 = arr1.copy()

In [14]:
## Addrress for both arrays are different now when we are making shallow copy 
print(id(arr1))
print(id(arr2))

2455267110960
2455267218736


In [16]:
## But if we change value in one array , it will change in another array as well.
arr1 = np.array([1,2,3,4])

In [17]:
# To avoid above problem we can use deep copy
arr2 = arr1.copy()

In [18]:
## But if we change value in one array , it will change in another array as well.
arr2[2] = 100
arr1[3] = 200
print(arr1)
print(arr2)

[  1   2   3 200]
[  1   2 100   4]


#### Deep Copy : value and address are independent for both array
#### Shallow Copy :  address are independent but value are dependent. 