# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [3]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [4]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [5]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [7]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [8]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [9]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.29330443 0.39512259 0.71367056 0.38009594 0.86785107]
 [0.00549232 0.3902481  0.72933909 0.3373087  0.33631839]
 [0.37293191 0.79258536 0.37187842 0.62301608 0.53027568]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]

[[-1.24578688  0.49633721 -0.0938787  -1.88640569 -1.33312507]
 [ 2.23233939  0.22667207 -0.18581709  1.04062703  1.50074678]
 [ 0.0314075  -1.07251519  1.538998   -0.77823944  0.74081445]
 [-0.72005747  0.12869181 -1.48427002 -0.32290392  1.2160871 ]
 [ 0.33973679 -0.00941917  0.15018569  0.83787215 -0.35204275]
 [ 2.24236496  0.62254086 -0.1780463  -0.59941736 -0.85521881]
 [-0.15495157  1.0956207   0.05788447  0.24695579  0.74577918]
 [-1.2221897  -1.35690723  0.36597218  1.64403967  0.94506801]
 [ 1.43724942 -0.18433301 -2.6516337  -0.43065766  0.13751131]
 [-1.11497199  0.07030748  0.31332356  0.0523044  -1.85730936]]


In [11]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.54277565  0.26872008 -0.94828423  0.48328922  0.57123486 -0.94603227
 -0.04614342 -1.88110401 -0.09201336 -0.22979893  0.6133874   0.36698999
 -0.36985539  0.98393285 -0.55636939 -0.42649208  0.45191664 -0.10769986
 -0.86197114]
-0.04614342010373825


In [12]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.57123486 -0.94603227 -0.04614342 -1.88110401 -0.09201336]


In [14]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))

print(rand_vec[np.arange(0,15,3)])   #[ 0  3  6  9 12] index value will be output

[ 0  3  6  9 12]
[ 0.54277565  0.48328922 -0.04614342 -0.22979893 -0.36985539]


In [18]:
# Access single value friom matrix

print(rand_mat)
print("")
print(rand_mat[1][2])   # rand_mat[row_index][column_index]   : this method work on numpy array and list as well.
print(rand_mat[1,2])    # rand_mat[row_index, column_index]   : this method work on numpy array only


[[0.29330443 0.39512259 0.71367056 0.38009594 0.86785107]
 [0.00549232 0.3902481  0.72933909 0.3373087  0.33631839]
 [0.37293191 0.79258536 0.37187842 0.62301608 0.53027568]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]

0.7293390867123992
0.7293390867123992


In [21]:
# get multiple values 
print(rand_mat[0:2,1:3])  # get rows 0,1 , columns = 1,2  

[[0.39512259 0.71367056]
 [0.3902481  0.72933909]]


In [22]:
#Set values in an array!
print(rand_vec)
rand_vec[3:5] = 4     # set index 3,4 = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]    # set 3rd index = 1, 5th index = 2
print('')
print(rand_vec)

[ 0.54277565  0.26872008 -0.94828423  0.48328922  0.57123486 -0.94603227
 -0.04614342 -1.88110401 -0.09201336 -0.22979893  0.6133874   0.36698999
 -0.36985539  0.98393285 -0.55636939 -0.42649208  0.45191664 -0.10769986
 -0.86197114]

[ 0.54277565  0.26872008 -0.94828423  4.          4.         -0.94603227
 -0.04614342 -1.88110401 -0.09201336 -0.22979893  0.6133874   0.36698999
 -0.36985539  0.98393285 -0.55636939 -0.42649208  0.45191664 -0.10769986
 -0.86197114]

[ 0.54277565  0.26872008 -0.94828423  1.          2.         -0.94603227
 -0.04614342 -1.88110401 -0.09201336 -0.22979893  0.6133874   0.36698999
 -0.36985539  0.98393285 -0.55636939 -0.42649208  0.45191664 -0.10769986
 -0.86197114]


In [23]:
print(rand_mat)
rand_mat[1:3,3:5] = 0     # set row 1,2 = 0 and  column = 4,5 = 0
print('')
print(rand_mat)

[[0.29330443 0.39512259 0.71367056 0.38009594 0.86785107]
 [0.00549232 0.3902481  0.72933909 0.3373087  0.33631839]
 [0.37293191 0.79258536 0.37187842 0.62301608 0.53027568]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]

[[0.29330443 0.39512259 0.71367056 0.38009594 0.86785107]
 [0.00549232 0.3902481  0.72933909 0.         0.        ]
 [0.37293191 0.79258536 0.37187842 0.         0.        ]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]


In [24]:
sub_mat = rand_mat[0:2,0:3]       # create sub natrix 
print(sub_mat)
sub_mat[:] = 3                    # set all value = 3
print(sub_mat)


[[0.29330443 0.39512259 0.71367056]
 [0.00549232 0.3902481  0.72933909]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.38009594 0.86785107]
 [3.         3.         3.         0.         0.        ]
 [0.37293191 0.79258536 0.37187842 0.         0.        ]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]


In [27]:
sub_mat2 = rand_mat[0:2,0:3].copy()    # deep copy (Changing value in sub_mat2 does not change rand_mat)
sub_mat2[:] = 99
print(sub_mat2) 
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.38009594 0.86785107]
 [3.         3.         3.         0.         0.        ]
 [0.37293191 0.79258536 0.37187842 0.         0.        ]
 [0.54688766 0.45500545 0.55143973 0.58066666 0.16984267]
 [0.80807055 0.76741813 0.41199233 0.9931135  0.87131166]]


In [28]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print("")
print(rand_vec>0) 
print("")
print(rand_vec[rand_vec>0])

[ 1.1175303  -0.75253015 -0.72949163  0.17672625  0.99579165  0.29219303
  1.19111777 -0.75258451 -0.1440908   0.33317728 -1.08982516 -1.11437102
  1.0669924   0.27813254  0.69315706]

[ True False False  True  True  True  True False False  True False False
  True  True  True]

[1.1175303  0.17672625 0.99579165 0.29219303 1.19111777 0.33317728
 1.0669924  0.27813254 0.69315706]


In [30]:
print(rand_mat2)
print("")
print(rand_mat2[rand_mat2>0])    # acces value which is greater than 0

[[-1.24578688  0.49633721 -0.0938787  -1.88640569 -1.33312507]
 [ 2.23233939  0.22667207 -0.18581709  1.04062703  1.50074678]
 [ 0.0314075  -1.07251519  1.538998   -0.77823944  0.74081445]
 [-0.72005747  0.12869181 -1.48427002 -0.32290392  1.2160871 ]
 [ 0.33973679 -0.00941917  0.15018569  0.83787215 -0.35204275]
 [ 2.24236496  0.62254086 -0.1780463  -0.59941736 -0.85521881]
 [-0.15495157  1.0956207   0.05788447  0.24695579  0.74577918]
 [-1.2221897  -1.35690723  0.36597218  1.64403967  0.94506801]
 [ 1.43724942 -0.18433301 -2.6516337  -0.43065766  0.13751131]
 [-1.11497199  0.07030748  0.31332356  0.0523044  -1.85730936]]

[0.49633721 2.23233939 0.22667207 1.04062703 1.50074678 0.0314075
 1.538998   0.74081445 0.12869181 1.2160871  0.33973679 0.15018569
 0.83787215 2.24236496 0.62254086 1.0956207  0.05788447 0.24695579
 0.74577918 0.36597218 1.64403967 0.94506801 1.43724942 0.13751131
 0.07030748 0.31332356 0.0523044 ]


In [32]:
# set all value to -5 which is less than 0.5

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5           
print(rand_vec)

[-5.         -0.75253015 -0.72949163  0.17672625 -5.          0.29219303
 -5.         -0.75258451 -0.1440908   0.33317728 -1.08982516 -1.11437102
 -5.          0.27813254 -5.        ]

[-5.         -0.75253015 -0.72949163  0.17672625 -5.          0.29219303
 -5.         -0.75258451 -0.1440908   0.33317728 -1.08982516 -1.11437102
 -5.          0.27813254 -5.        ]


In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)