In [1]:
from array import *

In [2]:
arr1 = array("i", [2,3,65])              # 1-D array
print(arr1)

array('i', [2, 3, 65])


In [4]:
arr2 = array("i", [3,5,6], [7,8,9])         # 2-D array

TypeError: array() takes at most 2 arguments (3 given)

#### While declaring 2-D array , it default array library is not allowing to do so.
#### Thus we need "NUMPY" to deal in multidimensional array.

In [21]:
import numpy as np

In [49]:
dtypetest = np.array([1,2,2))
dtypetest

array([1, 2, 2])

### There are 6 ways to create an array using numpy:
#### array()
#### linspace()
#### logspace()
#### arange()
#### zeros()
#### ones()

In [24]:
## Using array: 
# we can create numpy arrays by converting lists
# this is a vector
narr1 = np.array([1,2,3,4])
print(narr1)

# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)       # Transpose

[1 2 3 4]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [31]:
# Using linspace: Divide the range into some parts i.e. here 10 parts.
## If you dont specify parts than it will break into 50 parts which is default.

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]


In [26]:
## Using arange: Divide the range using steps i.e. here step by 6
## If we dont specify steps, than by default it will take 1 as step.

vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [37]:
## Using Numpy zeros:
mat2 = np.zeros([5,3])
print(mat2)

print("")
np_zeros = np.zeros(5)
print(np_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[0. 0. 0. 0. 0.]


In [36]:
## Using Numpy Ones:
mat3 = np.ones((3,5))
print('')
print(mat3)

print("")
np_ones = np.ones(5)
print(np_ones)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[1. 1. 1. 1. 1.]


In [39]:
#Using eye(Identy matrix)
mat4 = np.eye(5)
print('')
print(mat4)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
# we can (+-*/) arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)

print(vec5)
print("")
print(vec6)
print("")
print(vec5+vec6)
print("")
print(vec5*vec6)
print("")
print(1/vec5)
print("")
print(np.sqrt(vec6))
print("")

[1 2 3 4 5]

[3 4 5 6 7]

[ 4  6  8 10 12]

[ 3  8 15 24 35]

[1.         0.5        0.33333333 0.25       0.2       ]

[1.73205081 2.         2.23606798 2.44948974 2.64575131]



In [53]:
### Finding unique in numpy array
num_array = np.array([1,2,32,4,5,5,6,7,8,8,8])
print(np.unique(num_array))

[ 1  2  4  5  6  7  8 32]


In [85]:
# we can also use numpy to generate samples of a random variable and form a unifirm distribution
rand_val = np.random.rand(5)
print(rand_val)

print("")

rand_mat = np.random.rand(5,6)
print(rand_mat)

[0.03133871 0.13111084 0.78335578 0.69090239 0.40344108]

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 0.71103789 0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]


In [61]:
# we can also use numpy to generate samples of a random variable and form a normal distribution
normal_rand_val = np.random.randn(5)
print(normal_rand_val)

print("")

normal_rand_mat = np.random.randn(5,6)
print(normal_rand_mat)
print("")
print("Mean is {}".format(np.mean(normal_rand_mat)))
print("")
print("Std is {}".format(np.std(normal_rand_mat)))

[ 0.3460033  -0.76175681  1.25952006 -0.30871452 -1.55658811]

[[ 0.42663804 -0.49781354 -0.57142088 -1.29806263 -0.57137303  0.17003546]
 [-0.27469744 -0.47072473 -1.9075448   0.32388124  0.06647204  1.0380345 ]
 [ 0.56901395 -0.29873491  0.81899802 -1.59781674  1.96936741 -0.35967429]
 [ 0.51976184 -1.03263568 -0.99430574  1.93533376 -0.14823938 -0.28630823]
 [-0.24358211 -0.14807923 -1.36495098 -0.73986362 -0.23724721 -0.50708205]]

Mean is -0.1904206988826544

Mean is 0.8842292102762732


In [65]:
## Access one value from numpy array

arr_a = np.arange(19)
print(arr_a)
print("")
print(arr_a[8])     ## Access random value by its index

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

8


In [66]:
# we can access multiple entries at once using :
print(arr_a[3:10])

[3 4 5 6 7 8 9]


In [68]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,10,3))
print(arr_a[np.arange(0,15,3)])

[0 3 6 9]
[ 0  3  6  9 12]


In [73]:
# what about matrices
print(rand_mat)
print("")
print(rand_mat[1][2])
print("")
print("or do like below")
print(rand_mat[1,2])

[[0.84461245 0.90135095 0.87682196 0.26338572 0.15584524 0.08807785]
 [0.4392799  0.99740857 0.98494764 0.06365493 0.25828232 0.46035824]
 [0.46531897 0.1687643  0.82031427 0.76613192 0.82370957 0.78584186]
 [0.6943379  0.19228642 0.71992411 0.98383087 0.28056842 0.74588589]
 [0.51429828 0.60144026 0.7367821  0.4952116  0.12604276 0.81935263]]

0.9849476410038502

or do like below
0.9849476410038502


In [83]:
## Extract submatrix  : [row, column]

print(rand_mat[0:2,1:3])               ## first fetch row 0,1 then fetch column 1 and 2 from it
print("")
print(rand_mat[2, 3:5])                ## first fetch row 2 then fetch column 3 and 4

[[0.90135095 0.87682196]
 [0.99740857 0.98494764]]

[0.76613192 0.82370957]


In [86]:
## CHange some value in array
print(rand_mat)

rand_mat[2,2] = 1

print("")
print(rand_mat)

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 0.71103789 0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]


In [91]:
print(rand_mat[1,3])   ## fetching exact
print("")
print(rand_mat[1:3])   ## fetching range

0.4676444711541138

[[0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]]


In [92]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat)

In [102]:
np.savez('zipped_file_name',rand_mat=rand_mat)  ## use savez to save in compress form

## np.savez('zipped_file_name',rand_mat=rand_mat, rand_mat2 = rand_mat2)   ## to save many variables

In [103]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip['rand_mat'])
print('')
## print(loaded_zip['rand_mat2'])    ## If we save more variable in npz

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]



In [101]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]

[[0.79399057 0.18906469 0.72223663 0.19404066 0.26141455 0.117216  ]
 [0.11611325 0.80730204 0.23126289 0.46764447 0.12715128 0.45174847]
 [0.59165772 0.65147343 1.         0.52793333 0.39128424 0.82930296]
 [0.29008695 0.18636903 0.09842599 0.76647629 0.38363234 0.47441358]
 [0.8111951  0.45181199 0.94175013 0.85376239 0.65670324 0.35714091]]
